version: '3.3'
services:
  database:
    image: biarms/mysql:5.7
    container_name: bWAPP-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bug
    volumes:
      - ./volumes/database:/var/lib/mysql
  web:
    image: arm64v8/php:5-apache
    container_name: bWAPP-web
    restart: always
    ports:
      - 20080:80
    volumes:
      - ./web/bWAPP:/var/www
      - ./conf/apache2.conf:/etc/apache2/apache2.conf
      - ./conf/httpd.conf:/etc/apache2/httpd.conf
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
    command: "/bin/sh -c 'a2enmod dav dav_fs actions alias && docker-php-ext-install mysql mysqli pdo pdo_mysql && exec apache2-foreground'"
  phpmyadmin:
    image: phpmyadmin
    container_name: bWAPP-phpmyadmin
    restart: always
    ports:
      - 20088:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=bug